apiVersion: v1
kind: Pod
metadata:
  name: configmappod
spec:
  containers:
  - name: configmapcontainer
    image: redis
    env:
      - name: DBSERVER
        valueFrom:
          configMapKeyRef:
            name: myconfigmap
            key: db_host
      - name: DATABASE
        valueFrom:
          configMapKeyRef:
            name: myconfigmap
            key: database
    volumeMounts:
      - name: config-vol
        mountPath: "/config"
        readOnly: true
  volumes:
    - name: config-vol
      configMap:
        name: myconfigmap


#kubectl exec --it configmap -- printenv