apiVersion: v1
kind: Namespace
metadata:
  name: project
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-namespace
  namespace: project
spec:
  containers:
  - name: web-c1
    image: docker.io/murataksunet/k8s-web-helloo
    ports:
      - containerPort: 80



#kubectl create namespace app1
#kubectl get ns
#kubectl get namespaces
#kubectl get po -n app1
#kubectl delete ns app1
#
#kubectl apply -f pod-namespace.yaml
#kubectl get po -n project
#kubectl exec -it pod-namespace --namespace project  -- /bin/bash
#exit
#kubectl port-forward pod-namespace -n project 8080:80
#minikube dashboard
#kubectl delete pods --all -n project
#kubectl delete ns project
