apiVersion: v1
kind: Pod
metadata:
  name: nodeslctor-mysql
spec:
  nodeSelector:
    disktype: ssd
  containers:
  - name: env-mysql-demo
    image: mysql:5.6
    env:
    - name: MYSQL_USER
      value: "admin"
    - name: MYSQL_DATABASE
      value: "test-db"
    - name: MYSQL_ROOT_PASSWORD
      value: "onetwothree!"
    - name: MYSQL_HOST
      value: "mysql-service"
    - name: MYSQL_TCP_PORT
      value: "3306"
    ports:
    - containerPort: 3306

#minikube delete (3 node lu bir cluster kurmak için siliyoruz. (dockerdaki container silindi.))
#minikube start --nodes 3 (3 node lu bir cluster oluşturuyoruz. 1 master 2 worker node lu)
#minikube node list
#kubectl get nodes # bir master 2 worker olarak gösteriliyor.
#kubectl describe nodes
#kubectl label node minikube-m03 disktype=ssd  #farzedelim ki ..m-03 node unda ssd disk var label atayalım
#kubectl describe node minikube-m03
#kubectl apply -f nodeselector.yaml
#kubectl get po
#kubectl get po -o wide
#kubectl delete -f nodeselector.yaml 