apiVersion: v1
kind: Pod
metadata:
  name: pod-annotation
  annotations:
    owner: "İbrahim Kuş"
    email: "admin@ibrahimkus.net"
    releasedate: "01.01.2022"
    oncallPager: 111-222-3333
    imageregistry: "https://hub.docker.com"
    kbArticle: "https://kb.docs.example.com/KB123456"
spec:
  containers:
  - name: container
    image: nginx
    ports:
    - containerPort: 80