apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deploy
  labels:
    app: nginx
spec:
  replicas: 10
  strategy:
   type: Recreate #If not specified, it will be a rolling update 
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: web-deploy-pod
      labels:
        app: nginx
    spec:
      containers:
      - name: web-deploy-container
        image: nginx:1.14.2
        ports:
        - containerPort: 80


#kubectl create -f nginx-deployment.yaml 
#kubectl get all -l app=nginx
#kubectl describe deploy web-deploy
#we are specified strategy: type: Recreate  in yaml file. And then:
#kubectl apply -f nginx-deployment.yaml 
#kubectl rollout --help
#we are specified image: nginx:1.15.10 in yaml file.
#kubectl apply -f nginx-deployment.yaml 
#kubectl rollout status deployment/web-deploy
#kubectl rollout history deployment/web-deploy
#we are specified image: nginx:1.14.2 in yaml file.
#kubectl apply -f nginx-deployment.yaml 
#kubectl rollout history deployment/web-deploy
#kubectl describe deploy web-deploy
#ROLLBACK
#kubectl rollout undo deployment/web-deploy  =>return one step on revision.
#kubectl rollout undo deployment/web-deploy --to-revision=3 => return revision 3.

