apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: web-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-rs-demo
    matchExpressions:
      - {key: tier, operator: In, values: [frontend]}
  template:
    metadata:
      name: web-rs-pod
      labels:
        app: web-rs-demo
        tier: frontend
    spec:
      containers:
      - name: web-rs-container
        image: murataksunet/k8s-replicaset
        ports:
        - containerPort: 80



#kubectl create -f replicaset.yaml 
#kubectl get rs
#kubectl get replicaset -o wide
#kubectl get po -l app=web-rs-demo
#kubectl describe rs web-replicaset
#kubectl scale rs web-replicaset --replicas=6
#minikube dashboard
#kubectl port-forward web-replicaset-xxxxx 9080:80
#kubectl delete rs web-replicaset

