apiVersion: apps/v1
kind: Deployment
metadata:
  name: ru-rollout-deployment
  labels:
    app: web
spec:
  replicas: 20
  strategy:
   type: RollingUpdate
   rollingUpdate:
     maxUnavailable: 2
     maxSurge: 2
  minReadySeconds: 0
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - image: murataksunet/web-site-versions:v1
        name: web-container
        ports:
        - containerPort: 80

#kubectl apply -f rollingUpdate-rollout-deployment.yaml --record=true
#kubectl get all -l app=web
#kubectl port-forward pod/ru-rollout-deployment-5779b74d6-hl9jp 8080:80
#kubectl set image deployment/ru-rollout-deployment web-container=murataksunet/#web-site-versions:v2 --record=true
#kubectl get replicaset -w
#kubectl describe deploy/ru-rollout-deployment


