apiVersion: v1
kind: Pod
metadata:
  name: podenvironment
spec:
  containers:
  - name: env-mysql-demo
    image: mysql:5.6
    env:
    - name: MYSQL_USER
      value: "admin"
    - name: MYSQL_DATABASE
      value: "test-db"
    - name: MYSQL_ROOT_PASSWORD
      value: "onetwothree!"
    - name: MYSQL_HOST
      value: "mysql-service"
    - name: MYSQL_TCP_PORT
      value: "3306"
    ports:
    - containerPort: 3306

#kubectl apply -f pod-environment.yaml
#kubectl describe po podenvironment
#kubectl exec podenvironment -- printenv    