apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-first
  labels: #added later
    app: frontend #added later
spec:
  containers:
  - name: web
    image: nginx:latest
    ports:
    - containerPort: 80