apiVersion: v1
kind: Pod
metadata:
  name: cpu-demo
  namespace: cpu-mem-demo
spec:
  containers:
  - name: cpu-container
    image: vish/stress
    resources:
      limits:
        cpu: "1"
      requests:
        cpu: "0.5"
    args:
    - -cpus
    - "2"

#kubectl get ns
#kubectl create ns cpu-mem-demo
#kubectl get ns
#kubectl apply -f cpu-request-limit.yaml
#kubectl get po --namespace cpu-mem-demo
#kubectl get po cpu-demo --output=yaml --namespace=cpu-mem-demo
#kubectl top po cpu-demo -n cpu-mem-demo

