apiVersion: v1 
kind: Pod 
metadata: 
  name: memory-demo 
  namespace: cpu-mem-demo 
spec: 
  containers:
  - name: memory-container
    image: polinux/stress 
    resources: 
      limits: 
        memory: "200Mi" 
      requests: 
        memory: "100Mi" 
    command: ["stress"] 
    args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang", "1"] 

#kubectl apply -f memory-request-limit.yaml
#kubectl get po -n cpu-mem-demo
#kubectl get po -n cpu-mem-demo -o yaml >>>>yaml output

