apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-apache
  labels:
    app: apache
spec:
  replicas: 3
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache-container
        image: httpd
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-loadblncr-svc
  labels:
    app: apache
spec:
  selector:
    app: apache
  type: LoadBalancer
  ports:
    - nodePort: 31111
      port: 80
      targetPort: 80

#kubectl apply -f myapp-loadbalancersvc-dep.yaml 
#kubectl get svc,deploy,pod -l app=apache
#kubectl describe svc myapp-loadblncr-svc
#minikube service list
#minikube service --url myapp-loadblncr-svc
#LOADBALANCER TEST
#Open new Terminal
#>minikube tunnel #and then terminal must be open
#kubectl get svc,deploy,pod -l app=apache (external-ip was created.)
#open External-ip in browser!!!
#kubectl get all