apiVersion: v1
kind: Pod
metadata:
  name: myapp-nginx
  labels:
    app: mpapp
    tier: frontend
spec:
  containers:
    - name: web
      image: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-nodeport-svc
spec:
  type: NodePort
  selector:
    app: mpapp
    tier: frontend
  ports:
    - nodePort: 30008
      port: 80
      targetPort: 80


#kubectl apply -f mynginx-nodeportsvc-pod.yaml 
#kubectl get svc,pod
#kubectl describe service myapp-nodeport-svc
#minikube service list

