apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: webdep
  name: webdep
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: webdep
  type: NodePort
status:
  loadBalancer: {}
